# Generated by Django 4.1.4 on 2023-01-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna_mascota',
            name='imagen_blob',
        ),
        migrations.AddField(
            model_name='vacuna_mascota',
            name='imagen64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
