# Generated by Django 4.1.4 on 2023-01-14 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0002_alter_mascota_options_mascota_image_and_more'),
        ('vacuna', '0002_remove_vacuna_mascota_imagen_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='idpet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.mascota'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='iduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='imagen64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='idanimal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.animal'),
        ),
        migrations.DeleteModel(
            name='Vacuna_Mascota',
        ),
    ]
