# Generated by Django 4.1.4 on 2023-01-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0003_vacuna_fecha_vacuna_idpet_vacuna_iduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='lugar_vacuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
