# Generated by Django 4.1.4 on 2022-12-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direction', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=45)),
                ('age', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='media/user')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
