# Generated by Django 4.1.4 on 2023-01-19 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0002_alter_mascota_options_mascota_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('idtimline', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('S', 'Suspendido'), ('E', 'Espera')], max_length=1)),
                ('tipo', models.CharField(choices=[('F', 'Formulario'), ('W', 'Entrevista por whatsapp'), ('V', 'Visita al domicilio'), ('C', 'Firma de contrato'), ('E', 'Entrega'), ('S', 'Seguimiento')], max_length=1)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('idpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.mascota')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'timeline',
                'verbose_name_plural': 'timelines',
                'db_table': 'timeline',
            },
        ),
    ]
