# Generated by Django 4.1.4 on 2023-02-03 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('temaid', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tema',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faqid', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=100, null=True)),
                ('temaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.tema')),
            ],
            options={
                'db_table': 'faq',
            },
        ),
    ]
