# Generated by Django 4.1.4 on 2023-02-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='temaid',
            new_name='tema',
        ),
    ]
