# Generated by Django 4.1.4 on 2023-02-15 00:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('idrecompensa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcionInicial', models.CharField(max_length=200)),
                ('descripcionFinal', models.CharField(max_length=200)),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
                ('descuento', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/productos')),
                ('activo', models.BooleanField()),
                ('puntos', models.PositiveIntegerField()),
                ('canjeado', models.BooleanField()),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'db_table': 'recompensa',
            },
        ),
    ]
