# Generated by Django 4.1.4 on 2023-02-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recompensa', '0002_alter_recompensa_iduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recompensa',
            name='iduser',
        ),
    ]
