# Generated by Django 4.1.4 on 2023-02-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recompensa', '0003_remove_recompensa_iduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recompensa',
            name='canjeado',
        ),
    ]
