# Generated by Django 4.1.4 on 2023-02-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recompensa', '0004_remove_recompensa_canjeado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompensa',
            name='descuento',
            field=models.PositiveIntegerField(),
        ),
    ]
