# Generated by Django 4.1.4 on 2023-02-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recompensa', '0005_alter_recompensa_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompensa',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
