# Generated by Django 4.1.4 on 2022-12-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol_User',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol_User',
                'verbose_name_plural': 'Rol_Users',
                'db_table': 'rol_user',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direction', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=45)),
                ('age', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.rol_user')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
