# Generated by Django 4.1.4 on 2023-01-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AddField(
            model_name='mascota',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/pet'),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='mascota',
        ),
    ]
